config/routes.rb
Rails.application.routes.draw do
  resources :carts
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/new'
  resources :reviews
  resources :transactions
  resources :admins
  resources :users
  resources :books
  resources :sessions, only: [:new,:create,:destroy] 
  
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'signup', to: "users#new", as:'signup'
  get 'login', to: "sessions#new", as:'login'
  get 'logout', to: "sessions#destroy", as:'logout'
end

app/models/book.rb
class Book < ApplicationRecord

  validates :name, presence: true
  validates :author, presence: true
  validates :publisher, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :stock, presence: true, numericality: { only_integer: true }

  has_many :reviews, dependent: :delete_all
  has_many :transactions, dependent: :delete_all

  BOOK_FILTERS = %w[name author publisher price stock]

  scope :filter_by_name, -> (name) { where("name like ?", "#{name}%")}
  scope :filter_by_author, -> (author) { where("author like ?", "#{author}%")}
  scope :filter_by_publisher, -> (publisher) { where("publisher like ?", "#{publisher}%")}
  scope :filter_by_price, -> (price) { where price: price }
  scope :filter_by_stock, -> (stock) { where stock: stock }
  # scope :filter_by_average_rating, -> (average_rating) { where("average_rating > ?", average_rating) }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    # @books = Book.all
     puts params
    @books = Book.where(nil)
    @review = Review.all
    puts params
    if params[:book_filter].present?
      @books = Book.public_send("filter_by_#{params[:book_filter]}", params[:book_filter_value]) if params[:book_filter_value].present?
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    if current_user.email == "admin@gmail.com"
      @book = Book.new(book_params)

      respond_to do |format|
        if @book.save
          format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
          format.json { render :show, status: :created, location: @book }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to books_url, notice: "Cannot perform the action." }
        format.json { render :show, status: :ok, location: @book }
      end
    end

  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    if (current_user.email == "admin@gmail.com")
      respond_to do |format|

        if @book.update(book_params)
          format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
          format.html { redirect_to book_url(@book), notice: "Cannot perform the action." }
          format.json { render :show, status: :ok, location: @book }
      end
  end
    end
  # DELETE /books/1 or /books/1.json
  def destroy
    @book = Book.find(params[:id])
    if (current_user.email == "admin@gmail.com")
      @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
        format.json { head :no_content }
      end

    else
      respond_to do |format|
        format.html { redirect_to books_url, notice: "Cannot destroy book." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author, :publisher, :price, :stock)
    end
  end

app/helpers/books_helper.rb
module BooksHelper

  def get_book(book_id)
    return Book.find(book_id)
  end
  def buy_book(book_id, quantity)
    book = get_book(book_id)
    @semaphore ||= Mutex.new

    @semaphore.synchronize {
      # only one thread at a time can enter this block...
      if quantity <= book.stock
            book.stock -= quantity
            book.save
            return true
          end
    }

    return false
  end
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%#= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>
<br>
<%= turbo_frame_tag "books", class: "shadow overflow-hidden rounded border-b border-gray-200" do %>
  <%= form_with url: books_url, method: :get, data: { controller: "search-form", search_form_target: "form", turbo_frame: "filters" } do |form| %>
    <%= form.collection_select :book_filter,
                               Book::BOOK_FILTERS, :to_s, :to_s,
                                :include_blank => 'Filters',
                               :id => :book_filter
    %>
    <%= form.text_field :book_filter_value, placeholder: "Search here", value: params[:book_filter_value], class: "border border-blue-500 rounded p-2", :id => :book_filter_value %>
    <%= form.button "Search", class: "bg-blue-500 text-white p-2 rounded-sm" %>
  <% end %>

  <br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Price</th>
      <th>Stock</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.price %></td>
        <td><%= book.stock %></td>
        <td><%= @review.where("book_id=?",book.id).average(:rating) %></td>
        <td><%= link_to 'Show', book %></td>
<!--        <td><%#= link_to 'Buy', new_transaction_path(:book_id => book.id) %></td>-->
        <td><%= link_to 'Add to Cart/Buy', new_cart_path(:book_id => book.id) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= button_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Show Reviews', reviews_path(:book_id => book.id)%></td>
        <td>
          <%= link_to "Review this book", new_review_path(:book_id => book.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @book.stock %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>